export const queryKeys = {
  me: ['me'] as const,
  users: ['users'] as const,

  documents: (filters?: object) => ['documents', filters] as const,
  document: (id: string) => ['document', id] as const,
  classification: (docId: string) => ['classification', docId] as const,
  duplicates: (docId: string) => ['duplicates', docId] as const,
  documentFields: (docId: string) => ['documentFields', docId] as const,

  shipments: ['shipments'] as const,
  shipment: (id: string) => ['shipment', id] as const,
  shipmentDetail: (id: string) => ['shipmentDetail', id] as const,
  shipmentFields: (id: string) => ['shipmentFields', id] as const,
  shipmentFlags: (id: string, status?: string) => ['shipmentFlags', id, status] as const,
  activityLog: (id: string) => ['activityLog', id] as const,

  emailConnections: ['emailConnections'] as const,
  dashboard: ['dashboard'] as const,
  orgSettings: ['orgSettings'] as const,

  flagSuggestions: (flagId: string) => ['flagSuggestions', flagId] as const,

  intelFeed: (params?: object) => ['intelFeed', params] as const,
  intelSearch: (q: string, params?: object) => ['intelSearch', q, params] as const,
  intelArticle: (id: string) => ['intelArticle', id] as const,
  shipmentIntel: (shipmentId: string) => ['shipmentIntel', shipmentId] as const,
  intelInterests: ['intelInterests'] as const,
  intelAlerts: ['intelAlerts'] as const,
  intelSources: ['intelSources'] as const,

  intelNotificationPrefs: ['intelNotificationPrefs'] as const,
  intelTrending: (params?: object) => ['intelTrending', params] as const,
  intelHeatmap: (days: number) => ['intelHeatmap', days] as const,
  intelByEventType: (days: number) => ['intelByEventType', days] as const,
  intelTimeline: (days: number) => ['intelTimeline', days] as const,
  intelKnowledgeGraph: (subjectType: string, subjectValue: string) => ['intelKnowledgeGraph', subjectType, subjectValue] as const,
  intelJobs: (params?: object) => ['intelJobs', params] as const,
  tagsAutocomplete: (prefix: string) => ['tagsAutocomplete', prefix] as const,
  intelFilterOptions: ['intelFilterOptions'] as const,
  intelInterestTypes: ['intelInterestTypes'] as const,
  articleFeedback: (articleId: string) => ['articleFeedback', articleId] as const,
  personalizedSummary: (articleId: string) => ['personalizedSummary', articleId] as const,
  mySourcePreferences: ['mySourcePreferences'] as const,
  knowledgeGraphStats: ['knowledgeGraphStats'] as const,
  hsAutocomplete: (q: string) => ['hsAutocomplete', q] as const,
};
