services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - VITE_GOOGLE_CLIENT_ID
    environment:
      - BACKEND_URL=https://api.veritariffai.co
    restart: unless-stopped
    networks:
      - brokerai-web

networks:
  brokerai-web:
    external: true
